CREATE USER etudiant WITH PASSWORD '1234';
CREATE USER admin WITH PASSWORD 'admin123';

<<<<<<< HEAD
GRANT CONNECT ON DATABASE ecole TO etudiant, admin;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO etudiant;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
=======
GRANT CONNECT ON DATABASE cours TO etudiant, admin;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO etudiant;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
>>>>>>> 0f43d13a6d857fb06ce0359fb8c617a37ec59a23
